# Main site settings
title: Guava
subtitle: Google core libraries for Java
description: Google core libraries for Java
baseurl: /guava
url: http://google.github.io
permalink: /news/:year/:month/:day/:title/

markdown: kramdown

exclude:
- "bower.json"
- "Gemfile*"
- "README.md"
- "*.sh"

# Set by default by GitHub pages (can't be changed)
safe: true
lsi: false
# source: <top level directory>

# Set by default by GitHub pages (can be changed)
# highlighter: pygments
# github: <repository metadata> (https://help.github.com/articles/repository-metadata-on-github-pages/)

# Collections
collections:
 releases:
   output: true
   permalink: /:collection/:path/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default

# Release data
# Do not change! updaterelease.sh automatically updates these fields
latest_release: 18.0
latest_snapshot: 19.0-SNAPSHOT

# Miscellaneous data
email: guava-discuss@googlegroups.com
twitter_username: GoogleGuava
github_username:  google/guava
